# Generated by Django 2.0.7 on 2018-07-24 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOTT', 'Biberon'), ('FEED', 'Manger'), ('DIAP', 'Couche'), ('SLEE', 'Dodo')], max_length=4)),
                ('quantity', models.PositiveSmallIntegerField(default=70, help_text='Veuillez indiquer la quantité souhaitée', verbose_name='Quantité')),
                ('comment', models.TextField(max_length=1024, verbose_name='Commentaire')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_connection', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='Dernière connexion')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Romy', help_text='Veuillez saisir le prénom de votre enfant', max_length=32, verbose_name='Prénom')),
                ('api_key', models.CharField(max_length=36, unique=True, verbose_name="Clé d'API")),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Bébé',
                'verbose_name_plural': 'Bébés',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='baby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Baby'),
        ),
    ]
