# Generated by Django 2.0.7 on 2018-07-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_baby_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='comment',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=None, help_text='Veuillez indiquer la quantité souhaitée', null=True, verbose_name='Quantité'),
        ),
    ]
