# Generated by Django 2.0.7 on 2018-07-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20180725_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='feeding_period',
            field=models.PositiveSmallIntegerField(blank=True, default=60, help_text='Veuillez indiquer la période entre chaque biberon', null=True, verbose_name='Période entre chaque biberon'),
        ),
    ]
