# Generated by Django 2.0.7 on 2018-07-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20180725_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_date'], 'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_date',
            field=models.DateTimeField(verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('BOTT', 'Biberon'), ('BATH', 'Bain'), ('DIAP', 'Couche'), ('SLEE', 'Dodo')], help_text="Veuillez indiquer le type de l'activité", max_length=4),
        ),
    ]
