# Generated by Django 2.0.7 on 2018-07-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20180727_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Veuillez indiquer la quantité de lait bue par bébé', null=True, verbose_name='Quantité'),
        ),
    ]
