# Generated by Django 2.0.7 on 2018-08-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20180810_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Veuillez saisir votre email', max_length=254, verbose_name='Adresse email')),
            ],
            options={
                'verbose_name': 'Adresse email de la beta',
                'verbose_name_plural': 'Adresses email de la beta',
            },
        ),
    ]
