# Generated by Django 2.0.7 on 2018-08-14 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_betauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='betauser',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'inscription"),
            preserve_default=False,
        ),
    ]
