# Generated by Django 2.2.4 on 2019-08-12 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_activity_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('BOTTLE', 'Biberon'), ('BATH', 'Bain'), ('PEE', 'Pipi'), ('POOH', 'Popo'), ('SLEEP', 'Dodo'), ('BF_L', 'Sein gauche'), ('BF_R', 'Sein droit')], help_text="Veuillez indiquer le type de l'activité", max_length=6),
        ),
    ]
